executionLog | INFO flwr 2024-07-21 18:16:23,763 | app.py:178 | Starting Flower simulation, config: num_rounds=5, no round_timeout
executionLog | INFO flwr 2024-07-21 18:16:28,858 | app.py:213 | Flower VCE: Ray initialized with resources: {'memory': 3774485300.0, 'node:127.0.0.1': 1.0, 'object_store_memory': 1887242649.0, 'CPU': 20.0, 'node:__internal_head__': 1.0, 'GPU': 1.0}
executionLog | INFO flwr 2024-07-21 18:16:28,859 | app.py:219 | Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
executionLog | INFO flwr 2024-07-21 18:16:28,859 | app.py:242 | Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0.5}
executionLog | INFO flwr 2024-07-21 18:16:28,874 | app.py:288 | Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
executionLog | INFO flwr 2024-07-21 18:16:28,874 | server.py:92 | [INIT]
executionLog | INFO flwr 2024-07-21 18:16:28,874 | server.py:279 | Requesting initial parameters from one random client
executionLog | INFO flwr 2024-07-21 18:16:33,314 | server.py:285 | Received initial parameters from one random client
executionLog | INFO flwr 2024-07-21 18:16:33,314 | server.py:94 | Evaluating initial global parameters
executionLog | INFO flwr 2024-07-21 18:19:24,480 | app.py:178 | Starting Flower simulation, config: num_rounds=5, no round_timeout
executionLog | INFO flwr 2024-07-21 18:19:29,344 | app.py:213 | Flower VCE: Ray initialized with resources: {'object_store_memory': 1965066240.0, 'memory': 3930132480.0, 'node:127.0.0.1': 1.0, 'node:__internal_head__': 1.0, 'CPU': 20.0, 'GPU': 1.0}
executionLog | INFO flwr 2024-07-21 18:19:29,344 | app.py:219 | Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
executionLog | INFO flwr 2024-07-21 18:19:29,345 | app.py:242 | Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0.5}
executionLog | INFO flwr 2024-07-21 18:19:29,357 | app.py:288 | Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
executionLog | INFO flwr 2024-07-21 18:19:29,357 | server.py:92 | [INIT]
executionLog | INFO flwr 2024-07-21 18:19:29,358 | server.py:279 | Requesting initial parameters from one random client
executionLog | INFO flwr 2024-07-21 18:19:33,553 | server.py:285 | Received initial parameters from one random client
executionLog | INFO flwr 2024-07-21 18:19:33,553 | server.py:94 | Evaluating initial global parameters
executionLog | INFO flwr 2024-07-21 20:23:55,496 | app.py:178 | Starting Flower simulation, config: num_rounds=5, no round_timeout
executionLog | INFO flwr 2024-07-21 20:24:00,516 | app.py:213 | Flower VCE: Ray initialized with resources: {'CPU': 20.0, 'memory': 3865699124.0, 'object_store_memory': 1932849561.0, 'node:127.0.0.1': 1.0, 'node:__internal_head__': 1.0, 'GPU': 1.0}
executionLog | INFO flwr 2024-07-21 20:24:00,516 | app.py:219 | Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
executionLog | INFO flwr 2024-07-21 20:24:00,516 | app.py:242 | Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0.5}
executionLog | INFO flwr 2024-07-21 20:24:00,526 | app.py:288 | Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
executionLog | INFO flwr 2024-07-21 20:24:00,526 | server.py:92 | [INIT]
executionLog | INFO flwr 2024-07-21 20:24:00,527 | server.py:279 | Requesting initial parameters from one random client
executionLog | INFO flwr 2024-07-21 20:24:04,730 | server.py:285 | Received initial parameters from one random client
executionLog | INFO flwr 2024-07-21 20:24:04,731 | server.py:94 | Evaluating initial global parameters
executionLog | INFO flwr 2024-07-21 20:24:40,224 | server.py:97 | initial parameters (loss, other metrics): 23887.71473991871, {'accuracy': 0.1025}
executionLog | INFO flwr 2024-07-21 20:24:40,225 | server.py:110 | 
executionLog | INFO flwr 2024-07-21 20:24:40,225 | server.py:111 | [ROUND 1]
executionLog | INFO flwr 2024-07-21 20:24:40,227 | server.py:224 | configure_fit: strategy sampled 10 clients (out of 10)
executionLog | INFO flwr 2024-07-22 00:25:51,568 | app.py:178 | Starting Flower simulation, config: num_rounds=5, no round_timeout
executionLog | INFO flwr 2024-07-22 00:25:57,740 | app.py:213 | Flower VCE: Ray initialized with resources: {'node:127.0.0.1': 1.0, 'memory': 3559546062.0, 'object_store_memory': 1779773030.0, 'CPU': 20.0, 'node:__internal_head__': 1.0, 'GPU': 1.0}
executionLog | INFO flwr 2024-07-22 00:25:57,740 | app.py:219 | Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
executionLog | INFO flwr 2024-07-22 00:25:57,741 | app.py:242 | Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0.5}
executionLog | INFO flwr 2024-07-22 00:25:57,757 | app.py:288 | Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
executionLog | INFO flwr 2024-07-22 00:25:57,757 | server.py:92 | [INIT]
executionLog | INFO flwr 2024-07-22 00:25:57,757 | server.py:279 | Requesting initial parameters from one random client
executionLog | INFO flwr 2024-07-22 00:26:01,818 | server.py:285 | Received initial parameters from one random client
executionLog | INFO flwr 2024-07-22 00:26:01,819 | server.py:94 | Evaluating initial global parameters
executionLog | INFO flwr 2024-07-22 00:26:39,920 | server.py:97 | initial parameters (loss, other metrics): 24092.216104388237, {'accuracy': 0.1029}
executionLog | INFO flwr 2024-07-22 00:26:39,923 | server.py:110 | 
executionLog | INFO flwr 2024-07-22 00:26:39,923 | server.py:111 | [ROUND 1]
executionLog | INFO flwr 2024-07-22 00:26:39,923 | server.py:224 | configure_fit: strategy sampled 10 clients (out of 10)
executionLog | ERROR flwr 2024-07-22 00:26:40,514 | ray_client_proxy.py:85 | Traceback (most recent call last):
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'

executionLog | ERROR flwr 2024-07-22 00:26:40,516 | ray_client_proxy.py:86 | [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'
executionLog | ERROR flwr 2024-07-22 00:26:40,782 | ray_client_proxy.py:85 | Traceback (most recent call last):
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'

executionLog | ERROR flwr 2024-07-22 00:26:40,783 | ray_client_proxy.py:86 | [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'
executionLog | ERROR flwr 2024-07-22 00:26:41,118 | ray_client_proxy.py:85 | Traceback (most recent call last):
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'

executionLog | ERROR flwr 2024-07-22 00:26:41,120 | ray_client_proxy.py:86 | [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'
executionLog | ERROR flwr 2024-07-22 00:26:41,446 | ray_client_proxy.py:85 | Traceback (most recent call last):
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'

executionLog | ERROR flwr 2024-07-22 00:26:41,447 | ray_client_proxy.py:86 | [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'
executionLog | ERROR flwr 2024-07-22 00:26:41,749 | ray_client_proxy.py:85 | Traceback (most recent call last):
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'

executionLog | ERROR flwr 2024-07-22 00:26:41,750 | ray_client_proxy.py:86 | [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'
executionLog | ERROR flwr 2024-07-22 00:26:42,042 | ray_client_proxy.py:85 | Traceback (most recent call last):
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'

executionLog | ERROR flwr 2024-07-22 00:26:42,043 | ray_client_proxy.py:86 | [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'
executionLog | ERROR flwr 2024-07-22 00:26:42,306 | ray_client_proxy.py:85 | Traceback (most recent call last):
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'

executionLog | ERROR flwr 2024-07-22 00:26:42,307 | ray_client_proxy.py:86 | [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'
executionLog | ERROR flwr 2024-07-22 00:26:42,633 | ray_client_proxy.py:85 | Traceback (most recent call last):
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'

executionLog | ERROR flwr 2024-07-22 00:26:42,634 | ray_client_proxy.py:86 | [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'
executionLog | ERROR flwr 2024-07-22 00:26:42,809 | ray_client_proxy.py:85 | Traceback (most recent call last):
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'

executionLog | ERROR flwr 2024-07-22 00:26:42,810 | ray_client_proxy.py:86 | [36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=11536, ip=127.0.0.1, actor_id=016e47b875c0c12f23012d5a01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x00000228C5D30A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'
executionLog | ERROR flwr 2024-07-22 00:26:44,470 | ray_client_proxy.py:85 | Traceback (most recent call last):
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_client_proxy.py", line 73, in _submit_job
    out_mssg, updated_context = self.actor_pool.get_client_result(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 399, in get_client_result
    return self._fetch_future_result(cid)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 280, in _fetch_future_result
    res_cid, out_mssg, updated_context = ray.get(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientAppException): [36mray::ClientAppActor.run()[39m (pid=7032, ip=127.0.0.1, actor_id=071c1ca7beb1fb3dc52337ca01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001147D2F0A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=7032, ip=127.0.0.1, actor_id=071c1ca7beb1fb3dc52337ca01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001147D2F0A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'

executionLog | ERROR flwr 2024-07-22 00:26:44,471 | ray_client_proxy.py:86 | [36mray::ClientAppActor.run()[39m (pid=7032, ip=127.0.0.1, actor_id=071c1ca7beb1fb3dc52337ca01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001147D2F0A90>)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 98, in __call__
    return self._call(message, context)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\message_handler\message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\client\numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\src\FlowerClient.py", line 43, in fit
    self.testCode()
AttributeError: 'FlowerClient' object has no attribute 'testCode'. Did you mean: 'tesCode'?

The above exception was the direct cause of the following exception:

[36mray::ClientAppActor.run()[39m (pid=7032, ip=127.0.0.1, actor_id=071c1ca7beb1fb3dc52337ca01000000, repr=<flwr.simulation.ray_transport.ray_actor.ClientAppActor object at 0x000001147D2F0A90>)
  File "python\ray\_raylet.pyx", line 1418, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1498, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1424, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 1364, in ray._raylet.execute_task.function_executor
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\_private\function_manager.py", line 726, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 464, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\crime\Desktop\uni\firstLevelDegreeThesis\venv\lib\site-packages\flwr\simulation\ray_transport\ray_actor.py", line 64, in run
    raise ClientAppException(str(ex)) from ex
flwr.client.client_app.ClientAppException: 
Exception ClientAppException occurred. Message: 'FlowerClient' object has no attribute 'testCode'
executionLog | INFO flwr 2024-07-22 00:26:44,475 | server.py:238 | aggregate_fit: received 0 results and 10 failures
executionLog | INFO flwr 2024-07-22 00:29:35,706 | app.py:178 | Starting Flower simulation, config: num_rounds=5, no round_timeout
executionLog | INFO flwr 2024-07-22 00:29:41,070 | app.py:213 | Flower VCE: Ray initialized with resources: {'memory': 4646726862.0, 'node:127.0.0.1': 1.0, 'object_store_memory': 2323363430.0, 'GPU': 1.0, 'CPU': 20.0, 'node:__internal_head__': 1.0}
executionLog | INFO flwr 2024-07-22 00:29:41,071 | app.py:219 | Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
executionLog | INFO flwr 2024-07-22 00:29:41,071 | app.py:242 | Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0.5}
executionLog | INFO flwr 2024-07-22 00:29:41,087 | app.py:288 | Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
executionLog | INFO flwr 2024-07-22 00:29:41,088 | server.py:92 | [INIT]
executionLog | INFO flwr 2024-07-22 00:29:41,088 | server.py:279 | Requesting initial parameters from one random client
executionLog | INFO flwr 2024-07-22 00:29:44,976 | server.py:285 | Received initial parameters from one random client
executionLog | INFO flwr 2024-07-22 00:29:44,976 | server.py:94 | Evaluating initial global parameters
executionLog | INFO flwr 2024-07-22 00:30:24,070 | server.py:97 | initial parameters (loss, other metrics): 24272.565774917603, {'accuracy': 0.101}
executionLog | INFO flwr 2024-07-22 00:30:24,071 | server.py:110 | 
executionLog | INFO flwr 2024-07-22 00:30:24,071 | server.py:111 | [ROUND 1]
executionLog | INFO flwr 2024-07-22 00:30:24,072 | server.py:224 | configure_fit: strategy sampled 10 clients (out of 10)
executionLog | INFO flwr 2024-07-22 00:49:29,499 | app.py:178 | Starting Flower simulation, config: num_rounds=5, no round_timeout
executionLog | INFO flwr 2024-07-22 00:49:36,642 | app.py:213 | Flower VCE: Ray initialized with resources: {'node:127.0.0.1': 1.0, 'memory': 4369897883.0, 'object_store_memory': 2184948940.0, 'node:__internal_head__': 1.0, 'CPU': 20.0, 'GPU': 1.0}
executionLog | INFO flwr 2024-07-22 00:49:36,642 | app.py:219 | Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
executionLog | INFO flwr 2024-07-22 00:49:36,642 | app.py:242 | Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0.5}
executionLog | INFO flwr 2024-07-22 00:49:36,662 | app.py:288 | Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
executionLog | INFO flwr 2024-07-22 00:49:36,663 | server.py:92 | [INIT]
executionLog | INFO flwr 2024-07-22 00:49:36,663 | server.py:279 | Requesting initial parameters from one random client
executionLog | INFO flwr 2024-07-22 00:49:41,044 | server.py:285 | Received initial parameters from one random client
executionLog | INFO flwr 2024-07-22 00:49:41,045 | server.py:94 | Evaluating initial global parameters
executionLog | INFO flwr 2024-07-22 00:50:27,059 | server.py:97 | initial parameters (loss, other metrics): 23635.746824622154, {'accuracy': 0.1044}
executionLog | INFO flwr 2024-07-22 00:50:27,061 | server.py:110 | 
executionLog | INFO flwr 2024-07-22 00:50:27,061 | server.py:111 | [ROUND 1]
executionLog | INFO flwr 2024-07-22 00:50:27,062 | server.py:224 | configure_fit: strategy sampled 10 clients (out of 10)
executionLog | INFO flwr 2024-07-22 00:50:33,203 | server.py:238 | aggregate_fit: received 10 results and 0 failures
executionLog | WARNING flwr 2024-07-22 00:50:33,880 | fedavg.py:252 | No fit_metrics_aggregation_fn provided
executionLog | INFO flwr 2024-07-22 00:51:00,058 | server.py:129 | fit progress: (1, 23635.758232474327, {'accuracy': 0.1044}, 32.99766309990082)
executionLog | INFO flwr 2024-07-22 00:51:00,059 | server.py:176 | configure_evaluate: strategy sampled 10 clients (out of 10)
